#include <stdio.h>
#include <stdlib.h>
#include <limits.h>

int		main(void)
{
	int	ret;
	int c = 0;
	ret = ft_printf("haha %3c", 'c');
	ft_printf("ret = %d\n");
	ret = ft_printf("%.3c", 'c');
	ft_printf("ret = %d\n");
	ret = ft_printf("%.15c", 'c');
	ft_printf("ret = %d\n");
	ret = ft_printf("%15c", 'c');
	ft_printf("ret = %d\n");
	ret = ft_printf("%15.6c", 'c');
	ft_printf("ret = %d\n");
	ret = ft_printf("ca marche%.6c", 'c'); //debug
	ft_printf("ret = %d\n");
	ret = ft_printf("ca marche%.11c\n", 'c'); //debug
	ft_printf("ret = %d\n");
	ret = ft_printf("ca marche%15c\n", 'c'); //debug
	ft_printf("ret = %d\n");
	ret = ft_printf("ca marche%25s\n", "hello ca va"); //debug
	ft_printf("ret = %d\n");
	ret = ft_printf("ca marche%15.6s\n", "hello ca va"); //debug
	ft_printf("ret = %d\n");
	ret = ft_printf("%-25c\n", 'c');
	ft_printf("ret = %d\n");
	ret = ft_printf("%025c\n", 'c');
	ft_printf("ret = %d\n");
	ret = ft_printf("%-025c\n", 'c');
	ft_printf("ret = %d\n");
	ret = ft_printf("%0-25s\n", "hello ca va");
	ft_printf("ret = %d\n");
	ret = ft_printf("%.8d\n", 1254);
	ft_printf("ret = %d\n");
	ret = ft_printf("%02i\n", 12456);
	ft_printf("ret = %d\n");
	ret = ft_printf("%0-25i\n", 12456);
	ft_printf("ret = %d\n");
	ret = ft_printf("%25i\n", 12456);
	ft_printf("ret = %d\n");
	ret = ft_printf("%i\n", -12456);
	ft_printf("ret = %d\n");
	ret = ft_printf("%6.2d\n", -1);
	ft_printf("ret = %d\n");
	ret = ft_printf("%6.2d\n", -12);
	ft_printf("ret = %d\n");
	ret = ft_printf("%6.2d\n", -140);
	ft_printf("ret = %d\n");
	ret = ft_printf("%6.2d\n", -100800);
	ft_printf("ret = %d\n");
	ret = ft_printf("%6.6d\n", -12);
	ft_printf("ret = %d\n");
	ret = ft_printf("%p\n", NULL);
	ft_printf("ret = %d\n");
	ret = ft_printf("%20.15p\n", main);
	ft_printf("ret = %d\n");
	ret = ft_printf("%p\n", &c);
	ft_printf("ret = %d\n");
	ret = ft_printf("%u\n", -12456);
	ft_printf("ret = %d\n");
	ret = ft_printf("%6.2u\n", -1);
	ft_printf("ret = %d\n");
	ret = ft_printf("%6.2u\n", -12);
	ft_printf("ret = %d\n");
	ret = ft_printf("%6.2u\n", -140);
	ft_printf("ret = %d\n");
	ret = ft_printf("%6.2u\n", -100800);
	ft_printf("ret = %d\n");
	ret = ft_printf("%6.6u\n", -12);
	ft_printf("ret = %d\n");
	ret = ft_printf("%x\n", -0);
	ft_printf("ret = %d\n");
	ret = ft_printf("%20.15x\n", -265894122);
	ft_printf("ret = %d\n");
	ret = ft_printf("%x\n", -123456789);
	ft_printf("ret = %d\n");
	ret = ft_printf("%X\n", -0);
	ft_printf("ret = %d\n");
	ret = ft_printf("%20.15X\n", -265894122);
	ft_printf("ret = %d\n");
	ret = ft_printf("%X\n", -123456789);
	ft_printf("ret = %d\n");
	ret = ft_printf("%X\n", INT_MAX + 2);
	ft_printf("ret = %d\n");
	ret = ft_printf("%X\n", INT_MIN - 2);
	ft_printf("ret = %d\n");
	ret = ft_printf("%p\n", LONG_MAX + 2);
	ft_printf("ret = %d\n");
	ret = ft_printf("%p\n", LONG_MIN - 2);
	ft_printf("ret = %d\n");
	ret = ft_printf("%*.*d hello\n", 8, 5, 10);
	ft_printf("ret = %d\n");
	ret = ft_printf("ca marche%25s\n", NULL); //debug
	ft_printf("ret = %d\n");
	ret = ft_printf("ca marche%15.6s\n", NULL); //debug
	ft_printf("ret = %d\n");
	ret = ft_printf("%s\n", NULL); //debug
	ft_printf("ret = %d\n");
	ret = ft_printf("%15.6s\n", NULL); //debug
	ft_printf("ret = %d\n");
	ret = ft_printf("%.s\n", NULL); //debug
	ft_printf("ret = %d\n");
	ret = ft_printf("[ca marche%25c]\n", NULL); //debug
	ft_printf("ret = %d\n");
	ret = ft_printf("[ca marche%15.6c]\n", NULL); //debug
	ft_printf("ret = %d\n");
	ret = ft_printf("[%c]\n", NULL); //debug
	ft_printf("ret = %d\n");
	ret = ft_printf("[%15.6c]\n", NULL); //debug
	ft_printf("ret = %d\n");
	ret = ft_printf("[%.3c]\n", NULL); //debug
	ft_printf("ret = %d\n");
	ret = ft_printf("%s\n", '\0'); //debug
	ft_printf("ret = %d\n");
	ret = ft_printf("%c\n", '\0'); //debug
	ft_printf("ret = %d\n");
	return (0);
}
