#include <stdio.h>
#include <stdlib.h>
#include <limits.h>

int		main(void)
{
	int	ret;
	int c = 0;
	ret = printf("haha %3c", 'c');
	printf("ret = %d\n");
	ret = printf("%.3c", 'c');
	printf("ret = %d\n");
	ret = printf("%.15c", 'c');
	printf("ret = %d\n");
	ret = printf("%15c", 'c');
	printf("ret = %d\n");
	ret = printf("%15.6c", 'c');
	printf("ret = %d\n");
	ret = printf("ca marche%.6c", 'c'); //debug
	printf("ret = %d\n");
	ret = printf("ca marche%.11c\n", 'c'); //debug
	printf("ret = %d\n");
	ret = printf("ca marche%15c\n", 'c'); //debug
	printf("ret = %d\n");
	ret = printf("ca marche%25s\n", "hello ca va"); //debug
	printf("ret = %d\n");
	ret = printf("ca marche%15.6s\n", "hello ca va"); //debug
	printf("ret = %d\n");
	ret = printf("%-25c\n", 'c');
	printf("ret = %d\n");
	ret = printf("%025c\n", 'c');
	printf("ret = %d\n");
	ret = printf("%-025c\n", 'c');
	printf("ret = %d\n");
	ret = printf("%0-25s\n", "hello ca va");
	printf("ret = %d\n");
	ret = printf("%.8d\n", 1254);
	printf("ret = %d\n");
	ret = printf("%02i\n", 12456);
	printf("ret = %d\n");
	ret = printf("%0-25i\n", 12456);
	printf("ret = %d\n");
	ret = printf("%25i\n", 12456);
	printf("ret = %d\n");
	ret = printf("%i\n", -12456);
	printf("ret = %d\n");
	ret = printf("%6.2d\n", -1);
	printf("ret = %d\n");
	ret = printf("%6.2d\n", -12);
	printf("ret = %d\n");
	ret = printf("%6.2d\n", -140);
	printf("ret = %d\n");
	ret = printf("%6.2d\n", -100800);
	printf("ret = %d\n");
	ret = printf("%6.6d\n", -12);
	printf("ret = %d\n");
	ret = printf("%p\n", NULL);
	printf("ret = %d\n");
	ret = printf("%20.15p\n", main);
	printf("ret = %d\n");
	ret = printf("%p\n", &c);
	printf("ret = %d\n");
	ret = printf("%u\n", -12456);
	printf("ret = %d\n");
	ret = printf("%6.2u\n", -1);
	printf("ret = %d\n");
	ret = printf("%6.2u\n", -12);
	printf("ret = %d\n");
	ret = printf("%6.2u\n", -140);
	printf("ret = %d\n");
	ret = printf("%6.2u\n", -100800);
	printf("ret = %d\n");
	ret = printf("%6.6u\n", -12);
	printf("ret = %d\n");
	ret = printf("%x\n", -0);
	printf("ret = %d\n");
	ret = printf("%20.15x\n", -265894122);
	printf("ret = %d\n");
	ret = printf("%x\n", -123456789);
	printf("ret = %d\n");
	ret = printf("%X\n", -0);
	printf("ret = %d\n");
	ret = printf("%20.15X\n", -265894122);
	printf("ret = %d\n");
	ret = printf("%X\n", -123456789);
	printf("ret = %d\n");
	ret = printf("%X\n", INT_MAX + 2);
	printf("ret = %d\n");
	ret = printf("%X\n", INT_MIN - 2);
	printf("ret = %d\n");
	ret = printf("%p\n", LONG_MAX + 2);
	printf("ret = %d\n");
	ret = printf("%p\n", LONG_MIN - 2);
	printf("ret = %d\n");
	ret = printf("%*.*d hello\n", 8, 5, 10);
	printf("ret = %d\n");
	ret = printf("ca marche%25s\n", NULL); //debug
	printf("ret = %d\n");
	ret = printf("ca marche%15.6s\n", NULL); //debug
	printf("ret = %d\n");
	ret = printf("%s\n", NULL); //debug
	printf("ret = %d\n");
	ret = printf("%15.6s\n", NULL); //debug
	printf("ret = %d\n");
	ret = printf("%.s\n", NULL); //debug
	printf("ret = %d\n");
	ret = printf("[ca marche%25c]\n", NULL); //debug
	printf("ret = %d\n");
	ret = printf("[ca marche%15.6c]\n", NULL); //debug
	printf("ret = %d\n");
	ret = printf("[%c]\n", NULL); //debug
	printf("ret = %d\n");
	ret = printf("[%15.6c]\n", NULL); //debug
	printf("ret = %d\n");
	ret = printf("[%.3c]\n", NULL); //debug
	printf("ret = %d\n");
	ret = printf("%s\n", '\0'); //debug
	printf("ret = %d\n");
	ret = printf("%c\n", '\0'); //debug
	printf("ret = %d\n");
	return (0);
}
